### ISSUE TITLE
stdout and stderr

### ISSUE THREAD

**Issue by aarnaud** [MicahParks/jwkset#16]
Hi,
Just to track this behaviour.

I'm not sure about this, but it's seem the `println` [here](https://github.com/MicahParks/jwkset/blob/master/cmd/jwksetinfer/main.go#L140C2-L140C20)  write on the stderr. 

This is problematic to redirect output to a file and keep the log on stderr. 

Anthony,

**Comment by MicahParks** [comment]
Looks like `println` always writes to stderr. That wasn't top-of mine when writing the linked line.
https://pkg.go.dev/builtin#println

The `*slog.Logger` used this file also write to stderr, which isn't ideal for scripts.

Since it's inconvenient for scripts and it's meant to be a CLI tool, I'll change that line to write to stdout.

**Comment by MicahParks** [comment]
Please use `v0.5.10` for scripts. Thank you for opening the issue!

**Comment by aarnaud** [comment]
Thanks a lot, It's appreciate
